config/routes.rb
Rails.application.routes.draw do
  get '/about', to: "pages#about"
  #VERB '/path', to: "controller#action"
  get '/contact', to: "pages#contact", as: :contact_us

  # get '/', to: "pages#home"
  root to: "pages#home"

  get '/restaurants/:id', to: "restaurants#show", as: :restaurant

  get '/restaurants', to: "restaurants#index"
  post '/restaurants', to: "restaurants#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def home

  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  RESTAURANTS = {
    1 => { name: "Sichuan Citizen", address: "Ferguson Lane", category: "sichuan" },
    2 => { name: "Blue Frog", address: "Lujiazui", category: "burgers" }
  }

  def index
    # @restaurants = Restaurant.all
    @cuisines = %w(hunan sichuan japanese)
    @food_type = params[:food_type]
    if @food_type.blank?
      @restaurants = RESTAURANTS
    else
      @restaurants = RESTAURANTS.select { |id, r| r[:category] == @food_type  }
    end
  end

  def create
    # @restaurant = Restaurant.new(name:  params[:name], address: params[:address])
    # @restaurant.save
    raise
  end

  def show
    @id = params[:id].to_i
    @restaurant = RESTAURANTS[@id]
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Thespoon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <h3>Simple header</h3>
    <%= yield %>
    <footer>Made @ Le Wagon</footer>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Home Page</h1>
<form action="/restaurants" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="name" placeholder="Name">
  <input type="text" name="address" placeholder="Address">
  <input type="submit">
</form>

app/views/restaurants/index.html.erb
<h1>My Fave Restaurants</h1>
<ul>
  <% @restaurants.each do |id, r| %>
    <li>
      <%= r[:name] %> - <%= r[:address] %>
      (<%= link_to r[:name],  restaurant_path(id) %>)
    </li>
  <% end %>
</ul>
<h2>You Searched for <%= @food_type %></h2>
<form action="/restaurants" method="get">
  <input type="text" name="food_type" placeholder="Sichuan Food, etc">
  <input type="submit">
</form>
<%= link_to "Contact", contact_us_path %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant[:name] %></h1>